spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.hostinger.com
    username: noreply@javaazerbaycan.com
    password: Nurlan00.
    port: '587'


server:
  port: 8090
